version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:  
      - APP_NAME=go_app
      - APP_PORT=8080
      - DEBUG=true
      - DB_HOST=35.198.227.107
      - DB_PORT=5432
      - DB_DATABASE=default-go
      - DB_USER=cloud-default
      - DB_PASSWORD=t6u/gzYf7H-z\8RF
      - DB_SSLMODE=disable
    # command: http
